In [1]:
import h5py as hp
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from pandas.tools.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

C:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [2]:
chinese_niche_2=pd.read_hdf('chinese_niche.h5','a')
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='吉澤嘉代子']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='菅野義孝']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Nomiya Maki (野宮真貴)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Kenichi Kamio (神尾憲一)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='宗次郎']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='あらかじめ決められた恋人たちへ']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='庾澄慶+張韶涵 (Harlem Yu+Angela Cheung)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Ryota Fujimaki (藤巻亮太)	']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='土岐麻子']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='阿部芙蓉美']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='土岐麻子']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='阿部芙蓉美']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='土岐麻子']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='阿部芙蓉美']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Ryota Fujimaki (藤巻亮太)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='SAKURA FUJIWARA (藤原さくら)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Nao Matsushita (松下　奈緒)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='竹仲絵里']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Miho Fukuhara (福原美穂)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='清涼月系列']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='古川本舗']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Natsume Mito (三戸なつめ)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Reiya Yamaguchi (山口レイヤ)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Alice Sara Ott (アリス＝紗良・オット)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Kaori Moｃhida (持田香織)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='石原江里子']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Asuka Hayashi (林明日香)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Yuko Narisoko (成底ゆう子)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Kaori Moｃhida (持田香織)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Nana Kitade (北出菜奈)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='ACE OF SPADES × PKCZ feat. 登坂広臣']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Ryuichi Kawamrua (河村隆一)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Miki Imai (今井美樹)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Sala Kurokawa (黒川沙良)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Emi Fujita (藤田恵美)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='志田サマー新井サマー']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='姊妹電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='與陽光共舞']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='D.D(范曉萱媽媽) + 范曉萱']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='江漢聲+曾素芝']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='惡男宅急電電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='吳昊恩+The Daniel Ho Trio']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='四季的呢喃系列']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='鄧福如+陳道賢+陸侲曦']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='小酒館的情歌']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='葉振棠&葉麗儀 (Johnny Ip & Frances Yip)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='カラスは真っ白']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='吳昊恩+The Daniel Ho Trio']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Amamiya Sora(雨宮天)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Mayo Okamoto (岡本真夜)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Yasutaka Nakata (中田ヤスタカ)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='電影【念念】']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='依錚依靜']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Ryuichi Sakamoto (坂本 龍一)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Amamiya Sora(雨宮天)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='佐藤聡美']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='內田奈織']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='麥浚龍 & 謝安琪 (Juno Mak & Kay Tse)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='利特 X SUHO X Kassy X Cho, Young Soo']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='金曲重炫']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Hiroko Shimabukuro (島袋寛子)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='柏木広樹']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Jynken min (じゃんけん民)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='金希澈 & 金政模 X 輝人 (of MAMAMOO)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='北乃きい']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='查勞加盧']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='青木カレン']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Mirei Touyama (當山　みれい)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='小樽戀曲']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Yamazaki Masayoshi (山崎まさよし)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='黃韻玲+洪筠惠']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='杉恵ゆりか']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Kahara Tomomi (華原朋美)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='天堂牧場 電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Gotō Maki (後藤真希)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='陳武官 & 吳佩俞']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Della陽光元氣系列']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='真愛傳情系列']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='天使之翼電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='私．旅行-地平線上的留白']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='撞球小子電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='阿爾發全體藝人']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Verbal Jint+梁多一']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='寶藍']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='結婚好嗎?']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='第14屆赤弦獎決賽精選']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='查勞．巴西瓦里 (Chalaw Basiwali)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='汪小敏+曹格 (Gary+Tracy)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='奇人密碼:古羅布之謎 電影原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='原唱原曲']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='帶我去遠方電影原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='日安。波斯菊']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Hiro Shimono (下野 紘)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='美味關係電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='MIMI 電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='再見螢火蟲電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Chitose Hajime (元ちとせ)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='許靖韻&張致恆 (Angela Hui & Steven Cheung)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='牽牛花開的日子電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='きのこ帝国']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Ayano Mashiro (綾野ましろ)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='艾迴20年200曲']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='劉若英+嚴爵 (Rene Liu+ Yen-j)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Haruko Amano (Kyoko Koizumi) (天野春子 (小泉今日子))']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='王大文+魏如萱']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='陳展鵬 & 胡定欣 (Ruco Chan & Nancy Wu)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='西內麻里亞']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='森山　良子']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Ami Suzuki (鈴木亜美)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='陳建年+巴奈']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='未來的選擇電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Heritage X 鐘鉉(JONGHYUN)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Seiko Matsuda (松田聖子)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Akina Nakamori (中森明菜)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='TOMOMI ITANO (板野友美)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Hitomi Yaida (矢井田瞳)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='方力申 & 鄧麗欣 (Alex Fong & Stephy Tang)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Akina Nakamori (中森明菜)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='福氣又安康電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='范瑋琪+張韶涵+郭靜 (Fanfan Fan+Angela Cheung+Claire Kuo))']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='愛原創音樂合輯2']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='江美琪+光良']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='VA韓樂合輯']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Kiyoshi Maekawa (前川 清)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='戀愛占星音樂全精選']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='波麗士大人電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='香草戀人館電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='AMATSUKI (天月-あまつき-)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Meisa Kuroki (黒木メイサ)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='2006 MP3人氣超強總冠軍']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='瑰寶1949 電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='2006 MP3人氣超強總冠軍']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='含笑食堂電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='台灣音樂便當 (A Tasty Bento Box of Taiwanese Music)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Noriko Sakai (酒井法子)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='高校處世王 電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='我的祕密飯店 電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='側田&劉浩龍 (Justin Lo & Wilfred Lau)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='水瀬いのり']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='林俊傑+林志穎 (JJ Lin+Jimmy Lin)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='一頁台北 電影原聲大碟']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='電視劇《少年四大名捕》']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Minami Takahashi (高橋みなみ)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='電視劇《妻子的秘密》']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Minami Takahashi (高橋みなみ)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='KATO MILIYAH (加藤 ミリヤ)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Tomohisa Sako (佐香 智久)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='金希澈&金政模']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='跨世紀金曲精選']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!="Tokyo Girls' Style (東京女子流)"]
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='金希澈&金政模']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='心星的淚光電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='ゲスの極み乙女。']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='我們最愛的電影金曲']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='最幸福電視原聲帶_遇見幸福300天']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='我們最愛的電影金曲']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='華人碉堡音樂帝國3']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Shouta Aoi (蒼井翔太)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='華人碉堡音樂帝國3']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='我要變成硬柿子電視原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='華人碉堡音樂帝國3']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='騷人電影原聲帶']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='最佳廣告主題曲年鑑']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='洪榮宏+洪敬堯']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='咖啡香系列']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='台灣國家公園音樂系列']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='巷弄裡的那家書店 (電視原聲帶)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='Hideaki Tokunaga (德永英明)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='莊心妍+海哲明']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_name']!='韋禮安+郭靜 (Weibird Wei+Claire Kuo)']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_id']!='2966397']
chinese_niche_2=chinese_niche_2[chinese_niche_2['artist_id']!='6711966']
chinese_niche_2=chinese_niche_2.reset_index(drop=True)
chinese_niche_2.head()

  SP artist_id        artist_name  nich_Score  number sum_SP
0  2    195128          張超 (Juck)    0.901673  3989.0   4424
1  2   1225884     胡維納 (Hu Weina)    0.899228  2561.0   2848
2  2     11169  楊家成 (Jeremy Yang)    0.884244  2750.0   3110
3  2     10451                陳耀川    0.859443  1975.0   2298
4  2   1210233    楊祐寧 (Tony Yang)    0.827691  2176.0   2629

In [3]:
df=pd.read_hdf('Week_Number.h5','a')
df['Avg_Rank']=df[['Rank_First_Week','Rank_Second_Week','Rank_Third_Week','Rank_Forth_Week']].mean(axis=1)
df['Avg_First_Week']=df['First_Week']/4
df['Avg_Second_Week']=df['Second_Week']/7
df['Avg_Third_Week']=df['Third_Week']/7
df['Avg_Forth_Week']=df['Forth_Week']/7
df['Avg_Final_Week']=df['Final_Week']/5
df['Total_Number']=df[['First_Week','Second_Week','Third_Week','Forth_Week']].sum(axis=1)
df['Rank_number']=df['Total_Number'].rank(ascending=False,method='dense')
df['Rank_number']=df['Rank_number'].astype(str)
df['Rank_number']=df['Rank_number'].apply(lambda n:n[:n.index('.')])
df['Rank_number']=df['Rank_number'].astype('int64')
df['Avg_Number']=df.Total_Number/4
df['Max_Rank']=df[['Rank_First_Week','Rank_Second_Week','Rank_Third_Week','Rank_Forth_Week']].max(axis=1)
df['Min_Rank']=df[['Rank_First_Week','Rank_Second_Week','Rank_Third_Week','Rank_Forth_Week']].min(axis=1)
df['Avg_mid_Rank']=df[['Max_Rank','Min_Rank']].mean(axis=1)
df['sd']=df[[ 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week','Rank_Forth_Week']].std(axis=1,ddof=1)
df['median']=df[[ 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week','Rank_Forth_Week']].median(axis=1)
df['mad']=df[[ 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week','Rank_Forth_Week']].mad(axis=1)
df['variance']=df[[ 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week','Rank_Forth_Week']].var(axis=1,ddof=1)
df['First_Rank_Gap']=df['Rank_First_Week'].apply(lambda n:1 if n<=100 else 2 if n<=1000 else 3)
df['Second_Rank_Gap']=df['Rank_Second_Week'].apply(lambda n:1 if n<=100 else 2 if n<=1000 else 3)
df['Third_Rank_Gap']=df['Rank_Third_Week'].apply(lambda n:1 if n<=100 else 2 if n<=1000 else 3)
df['Forth_Rank_Gap']=df['Rank_Forth_Week'].apply(lambda n:1 if n<=100 else 2 if n<=1000 else 3)
df['Final_Rank_Gap']=df['Rank_Final_Week'].apply(lambda n:1 if n<=100 else 2 if n<=1000 else 3)
df['First']=df['First_Week']-df['Second_Week']
df['Second']=df['Second_Week']-df['Third_Week']
df['Third']=df['Third_Week']-df['Forth_Week']
df['First_tendency']=(df.Rank_Second_Week <df.Rank_First_Week).apply(lambda n : 'increase'if n ==True else 'decrease')
df['Second_tendency']=(df.Rank_Third_Week <df.Rank_Second_Week).apply(lambda n : 'increase'if n ==True else 'decrease')
df['Third_tendency']=(df.Rank_Forth_Week <df.Rank_Third_Week).apply(lambda n : 'increase'if n ==True else 'decrease')
df['Forth_tendency']=(df.Final_Week <df.Rank_Forth_Week).apply(lambda n : 'increase'if n ==True else 'decrease')
df.head(10)

,artist_id,Final_Week,First_Week,Forth_Week,Second_Week,Third_Week,Rank_First_Week,Rank_Second_Week,Rank_Third_Week,Rank_Forth_Week,...,Third_Rank_Gap,Forth_Rank_Gap,Final_Rank_Gap,First,Second,Third,First_tendency,Second_tendency,Third_tendency,Forth_tendency
0,1,30107,26037,47217,48594,46548,550,516,529,522,...,2,2,2,-22557,2046,-669,increase,decrease,increase,decrease
1,10,49064,42541,69862,76957,71259,387,380,399,402,...,2,2,2,-34416,5698,1397,increase,decrease,decrease,decrease
2,1000,6542,6720,10402,10831,10717,1402,1485,1475,1517,...,3,3,3,-4111,114,315,decrease,increase,decrease,decrease
8,1000113,4,6,16,3,9,4299,5248,5222,5232,...,3,3,3,3,-6,-7,decrease,increase,decrease,increase
9,1000131,43,44,50,118,67,4261,5133,5164,5198,...,3,3,3,-74,51,17,decrease,decrease,decrease,increase
11,1000152,16,22,25,29,48,4283,5222,5183,5223,...,3,3,3,-7,-19,23,decrease,increase,decrease,increase
23,1000317,44,303,49,62,42,4002,5189,5189,5199,...,3,3,3,241,20,-7,decrease,decrease,decrease,increase
28,1000383,3,2,8,8,9,4303,5243,5222,5240,...,3,3,3,-6,-1,1,decrease,increase,decrease,increase
30,1000419,31,12,31,5,7,4293,5246,5224,5217,...,3,3,3,7,-2,-24,decrease,increase,increase,increase
39,1000515,1545,1522,2652,2420,3491,2926,3221,2702,3109,...,3,3,3,-898,-1071,839,decrease,increase,decrease,increase

In [4]:
df_count=pd.melt(df, id_vars=['artist_id'], value_vars=['First_tendency','Second_tendency','Third_tendency'])
df_count=df_count.groupby(['artist_id','value']).count().reset_index()
df_count=df_count.pivot(index='artist_id', columns='value', values='variable').reset_index().rename_axis(None, axis=1)
df_count.head()

  artist_id  decrease  increase
0         1       1.0       2.0
1        10       2.0       1.0
2      1000       2.0       1.0
3   1000113       2.0       1.0
4   1000131       3.0       NaN

In [5]:
df_count=df_count.fillna(0)
df_count['decrease']=df_count['decrease'].astype('int64')
df_count['increase']=df_count['increase'].astype('int64')
df_count.head()

  artist_id  decrease  increase
0         1         1         2
1        10         2         1
2      1000         2         1
3   1000113         2         1
4   1000131         3         0

In [6]:
df2=df.merge(df_count, on='artist_id', how='left')
df2['P_decrease']=(df2.decrease/(df2.decrease+df2.increase))
df2['P_increase']=(df2.increase/(df2.decrease+df2.increase))
df2

,artist_id,Final_Week,First_Week,Forth_Week,Second_Week,Third_Week,Rank_First_Week,Rank_Second_Week,Rank_Third_Week,Rank_Forth_Week,...,Second,Third,First_tendency,Second_tendency,Third_tendency,Forth_tendency,decrease,increase,P_decrease,P_increase
0,1,30107,26037,47217,48594,46548,550,516,529,522,...,2046,-669,increase,decrease,increase,decrease,1,2,0.333333,0.666667
1,10,49064,42541,69862,76957,71259,387,380,399,402,...,5698,1397,increase,decrease,decrease,decrease,2,1,0.666667,0.333333
2,1000,6542,6720,10402,10831,10717,1402,1485,1475,1517,...,114,315,decrease,increase,decrease,decrease,2,1,0.666667,0.333333
3,1000113,4,6,16,3,9,4299,5248,5222,5232,...,-6,-7,decrease,increase,decrease,increase,2,1,0.666667,0.333333
4,1000131,43,44,50,118,67,4261,5133,5164,5198,...,51,17,decrease,decrease,decrease,increase,3,0,1.000000,0.000000
5,1000152,16,22,25,29,48,4283,5222,5183,5223,...,-19,23,decrease,increase,decrease,increase,2,1,0.666667,0.333333
6,1000317,44,303,49,62,42,4002,5189,5189,5199,...,20,-7,decrease,decrease,decrease,increase,3,0,1.000000,0.000000
7,1000383,3,2,8,8,9,4303,5243,5222,5240,...,-1,1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
8,1000419,31,12,31,5,7,4293,5246,5224,5217,...,-2,-24,decrease,increase,increase,increase,1,2,0.333333,0.666667
9,1000515,1545,1522,2652,2420,3491,2926,3221,2702,3109,...,-1071,839,decrease,increase,decrease,increase,2,1,0.666667,0.333333
10,1000530,32,2,149,21,35,4303,5230,5196,5099,...,-14,-114,decrease,increase,increase,increase,1,2,0.333333,0.666667
11,1000611,40,20,35,39,27,4285,5212,5204,5213,...,12,-8,decrease,increase,decrease,increase,2,1,0.666667,0.333333
12,1000686,320,214,335,369,394,4091,4882,4837,4913,...,-25,59,decrease,increase,decrease,increase,2,1,0.666667,0.333333
13,1000719,6,15,83,179,183,4290,5072,5048,5165,...,-4,100,decrease,increase,decrease,increase,2,1,0.666667,0.333333
14,1000737,18,15,39,26,40,4290,5225,5191,5209,...,-14,1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
15,1000755,5,1,4,6,3,4304,5245,5228,5244,...,3,-1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
16,1000815,91,81,166,203,207,4224,5048,5024,5082,...,-4,41,decrease,increase,decrease,increase,2,1,0.666667,0.333333
17,1000842,186,168,286,222,272,4137,5029,4959,4962,...,-50,-14,decrease,increase,decrease,increase,2,1,0.666667,0.333333
18,1000941,1,1,6,6,5,4304,5245,5226,5242,...,1,-1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
19,1000956,13,8,10,31,25,4297,5220,5206,5238,...,6,15,decrease,increase,decrease,increase,2,1,0.666667,0.333333
20,1001016,3,4,24,25,31,4301,5226,5200,5224,...,-6,7,decrease,increase,decrease,increase,2,1,0.666667,0.333333
21,1001064,4,6,2,6,3,4299,5245,5228,5246,...,3,1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
22,1001118,10,14,22,35,29,4291,5216,5202,5226,...,6,7,decrease,increase,decrease,increase,2,1,0.666667,0.333333
23,1001136,20,3,1,3,1,4302,5248,5230,5247,...,2,0,decrease,increase,decrease,increase,2,1,0.666667,0.333333
24,1001178,7,16,17,26,13,4289,5225,5218,5231,...,13,-4,decrease,increase,decrease,increase,2,1,0.666667,0.333333
25,10012,151,16,34,42,27,4289,5209,5204,5214,...,15,-7,decrease,increase,decrease,increase,2,1,0.666667,0.333333
26,1001205,153,125,178,208,220,4180,5043,5011,5070,...,-12,42,decrease,increase,decrease,increase,2,1,0.666667,0.333333
27,1001277,3,3,7,1,6,4302,5250,5225,5241,...,-5,-1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
28,1001361,3,1,4,2,3,4304,5249,5228,5244,...,-1,-1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
29,1001502,12,48,43,84,31,4257,5167,5200,5205,...,53,-12,decrease,decrease,decrease,increase,3,0,1.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49060,999201,141,313,314,280,273,3992,4971,4958,4934,...,7,-41,decrease,increase,increase,increase,1,2,0.333333,0.666667
49061,999207,906,937,1511,1808,1620,3379,3589,3719,3811,...,188,109,decrease,decrease,decrease,increase,3,0,1.000000,0.000000
49062,999216,909,735,1323,1503,1115,3572,3823,4139,3967,...,388,-208,decrease,decrease,increase,increase,2,1,0.666667,0.333333
49063,999225,95231,89866,147234,145355,145645,224,241,231,230,...,-290,-1589,decrease,increase,increase,decrease,1,2,0.333333,0.666667
49064,999270,1,16,5,4,1,4289,5247,5230,5243,...,3,-4,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49065,999285,3,1,1,6,6,4304,5245,5225,5247,...,0,5,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49066,999369,1,1,2,2,4,4304,5249,5227,5246,...,-2,2,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49067,999387,7,9,18,24,19,4296,5227,5212,5230,...,5,1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49068,999390,425,336,607,574,652,3969,4677,4580,4642,...,-78,45,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49069,999402,10,4,17,10,9,4301,5241,5222,5231,...,1,-8,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49070,999456,14,2,16,13,10,4303,5238,5221,5232,...,3,-6,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49071,999519,6,1,14,10,15,4304,5241,5216,5234,...,-5,1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49072,999531,729,650,1087,1284,1116,3655,4002,4138,4174,...,168,29,decrease,decrease,decrease,increase,3,0,1.000000,0.000000
49073,999549,271,294,362,444,351,4011,4807,4880,4886,...,93,-11,decrease,decrease,decrease,increase,3,0,1.000000,0.000000
49074,999591,8,5,17,16,8,4300,5235,5223,5231,...,8,-9,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49075,9996,42237,35285,54505,62666,58918,445,443,453,473,...,3748,4413,increase,decrease,decrease,decrease,2,1,0.666667,0.333333
49076,999633,5448,4833,8336,9056,10314,1697,1653,1521,1738,...,-1258,1978,increase,increase,decrease,decrease,1,2,0.333333,0.666667
49077,999657,45,75,91,59,90,4230,5192,5141,5157,...,-31,-1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49078,999714,64,91,66,136,116,4214,5115,5115,5182,...,20,50,decrease,decrease,decrease,increase,3,0,1.000000,0.000000
49079,999720,6,6,5,13,6,4299,5238,5225,5243,...,7,1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49080,999756,6,8,4,12,27,4297,5239,5204,5244,...,-15,23,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49081,999762,95,73,89,102,164,4232,5149,5067,5159,...,-62,75,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49082,999768,9,5,15,1,23,4300,5250,5208,5233,...,-22,8,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49083,999783,7,1,2,1,1,4304,5250,5230,5246,...,0,-1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49084,999789,1,7,19,8,6,4298,5243,5225,5229,...,2,-13,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49085,999843,1,2,1,10,3,4303,5241,5228,5247,...,7,2,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49086,999867,1,1,2,6,5,4304,5245,5226,5246,...,1,3,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49087,999873,8,3,8,3,11,4302,5248,5220,5240,...,-8,3,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49088,999894,12,10,13,12,14,4295,5239,5217,5235,...,-2,1,decrease,increase,decrease,increase,2,1,0.666667,0.333333
49089,999996,1,2,4,1,3,4303,5250,5228,5244,...,-2,-1,decrease,increase,decrease,increase,2,1,0.666667,0.333333

In [7]:
df2.columns

Index(['artist_id', 'Final_Week', 'First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
       'Rank_Forth_Week', 'Rank_Final_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week', 'Avg_Final_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap', 'Final_Rank_Gap',
       'First', 'Second', 'Third', 'First_tendency', 'Second_tendency',
       'Third_tendency', 'Forth_tendency', 'decrease', 'increase',
       'P_decrease', 'P_increase'],
      dtype='object')

In [ ]:
df2.corr('pearson')

In [ ]:
df2.corr('kendall')

In [ ]:
df2.corr('spearman')

In [8]:

df3=df2[df2['artist_id'].isin(chinese_niche_2.artist_id)]
df2=df2[~df2['artist_id'].isin(chinese_niche_2.artist_id)]

In [9]:

df2['Pos']=df2['Final_Week'].apply(lambda n:'10%' if n>=28245 else 
                                          '20%' if n>=15548 else 
                                          '30%' if n>=8606 else 
                                          '40%' if n>=5518 else 
                                          '50%' if n>=3947 
                                          #'60%' if n>=2945 else 
                                          #'70%' if n>=2096 else 
                                         # '80%' if n>=1452 else 
                                          else'low_50%')
df3['Pos']=df3['Final_Week'].apply(lambda n:'10%' if n>=28245 else 
                                          '20%' if n>=15548 else 
                                          '30%' if n>=8606 else 
                                          '40%' if n>=5518 else 
                                          '50%' if n>=3947 
                                          #'60%' if n>=2945 else 
                                          #'70%' if n>=2096 else 
                                         # '80%' if n>=1452 else 
                                          else'low_50%')

#df3['Pos']=df3['Final_Week'].apply(lambda n:'90%' if n<910  else'80%' if n<1453 else '70%' if n<2097  else '60%' if n<2946 else  '50%' if n<3948 else  '40%' if n<5519 else '30%' if n<8607 else '20%' if n<15549  else '10%' if n<28246  else '100%')
df3.head()

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()

,artist_id,Final_Week,First_Week,Forth_Week,Second_Week,Third_Week,Rank_First_Week,Rank_Second_Week,Rank_Third_Week,Rank_Forth_Week,...,Third,First_tendency,Second_tendency,Third_tendency,Forth_tendency,decrease,increase,P_decrease,P_increase,Pos
46,10028,3186,2765,5396,4977,4725,2262,2280,2319,2199,...,-671,decrease,decrease,increase,decrease,2,1,0.666667,0.333333,low_50%
48,1003,2995,2973,4293,4819,4687,2182,2322,2336,2497,...,394,decrease,decrease,decrease,decrease,3,0,1.000000,0.000000,low_50%
64,10040,562,422,821,592,676,3883,4659,4556,4429,...,-145,decrease,increase,increase,increase,1,2,0.333333,0.666667,low_50%
77,10054,1236,871,1506,1866,1570,3441,3544,3757,3816,...,64,decrease,decrease,decrease,increase,3,0,1.000000,0.000000,low_50%
78,10058,578,595,840,910,1064,3710,4349,4185,4411,...,224,decrease,increase,decrease,increase,2,1,0.666667,0.333333,low_50%

# Split_validation

In [ ]:
#'First_tendency', 'Second_tendency', 'Third_tendency',

X = df3.loc[:,['Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',#'First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 
        'Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',#'First_tendency', 'Second_tendency', 'Third_tendency', 
       'P_decrease', 'P_increase']].values
'''
X = df.loc[:,[ 'First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
       'Rank_Forth_Week', 'Total_Number',
       'Rank_number', 'Avg_Number', 'Avg_Number_Rank', 'Max_Rank', 'Min_Rank']].values
'''
Y = df3.loc[:,['Pos']].values
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

# Rank

In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
'''
X=X_train
Y=Y_train
x=X_validation
y=Y_validation
'''

X = df2.loc[:,['Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
       'Third_Week','Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',
       'P_decrease', 'P_increase']].values
Y = df2.loc[:,['Pos']].values
x = df3.loc[:,['Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
       'Third_Week', 'Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase', 
       'P_decrease', 'P_increase']].values
y = df3.loc[:,['Pos']].values

clrTree = tree.DecisionTreeClassifier(criterion='gini',max_depth=6,min_samples_split=10)
clrTree = clrTree.fit(X, Y)
outTree = clrTree.predict(x)
#algorithm : {‘auto’, ‘ball_tree’, ‘kd_tree’, ‘brute’
clrKN = KNeighborsClassifier(n_neighbors=20)
clrKN = clrKN.fit(X, Y)
outKN = clrKN.predict(x)

# Prediction accuracy
print("Accuracy for Decision Tree Classifier: " + str(accuracy_score(y, outTree)*100)+"%")
print("Accuracy for KNeighbors Classifier: " + str(accuracy_score(y, outKN)*100)+"%") 
#print("Score for Decision Classifier: " + str(score(X_test,y_test['target'])))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:36: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Accuracy for Decision Tree Classifier: 95.5991875423155%
Accuracy for KNeighbors Classifier: 95.73459715639811%

In [ ]:
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(max_depth=10,random_state=7)
regressor = regressor.fit(X, Y)
out=regressor.predict(x)
print(regressor.score(X,Y))
print(regressor.score(x,y))

# Gap

In [ ]:
#'First_tendency', 'Second_tendency', 'Third_tendency',

X = df3.loc[:,['First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
        'Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',#'First_tendency', 'Second_tendency', 'Third_tendency', 
       'P_decrease', 'P_increase']].values
'''
X = df.loc[:,[ 'First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
       'Rank_Forth_Week', 'Total_Number',
       'Rank_number', 'Avg_Number', 'Avg_Number_Rank', 'Max_Rank', 'Min_Rank']].values
'''
Y = df3.loc[:,['Final_Rank_Gap']].values
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [18]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

X = df2.loc[:,['Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',#'First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 
        'Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',#'First_tendency', 'Second_tendency', 'Third_tendency', 
       'P_decrease', 'P_increase']].values
Y = df2.loc[:,['Final_Rank_Gap']].values
x = df3.loc[:,['Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',#'First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 
        'Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',#'First_tendency', 'Second_tendency', 'Third_tendency', 
       'P_decrease', 'P_increase']].values
y = df3.loc[:,['Final_Rank_Gap']].values


clrTree = tree.DecisionTreeClassifier(criterion='gini',max_depth=6,min_samples_split=10)
clrTree = clrTree.fit(X, Y)
outTree = clrTree.predict(x)
#algorithm : {‘auto’, ‘ball_tree’, ‘kd_tree’, ‘brute’
clrKN = KNeighborsClassifier(n_neighbors=20)
clrKN = clrKN.fit(X, Y)
outKN = clrKN.predict(x)

# Prediction accuracy
print("Accuracy for Decision Tree Classifier: " + str(accuracy_score(y, outTree)*100)+"%")
print("Accuracy for KNeighbors Classifier: " + str(accuracy_score(y, outKN)*100)+"%") 
#print("Score for Decision Classifier: " + str(score(X_test,y_test['target'])))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:31: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Accuracy for Decision Tree Classifier: 99.1875423155044%
Accuracy for KNeighbors Classifier: 99.45836154366961%

#  increase

In [ ]:
#'First_tendency', 'Second_tendency', 'Third_tendency',

X = df3.loc[:,['Forth_Week']].values
'''
X = df.loc[:,[ 'First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
       'Rank_Forth_Week', 'Total_Number',
       'Rank_number', 'Avg_Number', 'Avg_Number_Rank', 'Max_Rank', 'Min_Rank']].values
'''
Y = df3.loc[:,['Forth_tendency']].values
validation_size = 0.20
seed = 7
X_train, X_validation, Y_train, Y_validation = model_selection.train_test_split(X, Y, test_size=validation_size, random_state=seed)

In [19]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
X = df2.loc[:,['Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
       'Third_Week', 'Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',
       'P_decrease', 'P_increase']].values
Y = df2.loc[:,['Forth_tendency']].values
x = df3.loc[:,['Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',#'First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 
        'Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',#'First_tendency', 'Second_tendency', 'Third_tendency', 
       'P_decrease', 'P_increase']].values
y = df3.loc[:,['Forth_tendency']].values

clrTree = tree.DecisionTreeClassifier(criterion='gini',max_depth=6,min_samples_split=10)
clrTree = clrTree.fit(X, Y)
outTree = clrTree.predict(x)
#algorithm : {‘auto’, ‘ball_tree’, ‘kd_tree’, ‘brute’
clrKN = KNeighborsClassifier(n_neighbors=20)
clrKN = clrKN.fit(X, Y)
outKN = clrKN.predict(x)

# Prediction accuracy
print("Accuracy for Decision Tree Classifier: " + str(accuracy_score(y, outTree)*100)+"%")
print("Accuracy for KNeighbors Classifier: " + str(accuracy_score(y, outKN)*100)+"%") 
#print("Score for Decision Classifier: " + str(score(X_test,y_test['target'])))

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:29: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

Accuracy for Decision Tree Classifier: 97.0209884901828%
Accuracy for KNeighbors Classifier: 97.291807718348%

In [ ]:
print(classification_report(Y_validation,outTree))

In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
y_pred = gnb.fit(X, Y).predict(x)
# Calculate Accuracy Rate by using accuracy_score()
print("Accuracy Rate, which is calculated by accuracy_score() is: %f" % accuracy_score(y, y_pred))

In [ ]:
from sklearn import cross_validation, ensemble, preprocessing, metrics
# 建立 random forest 模型
forest = ensemble.RandomForestClassifier(n_estimators = 20)
forest_fit = forest.fit(X, Y)

# 預測
test_y_predicted = forest.predict(x)

# 績效
accuracy = metrics.accuracy_score(y, test_y_predicted)
print(accuracy)

## View

In [11]:
outTree = np.array(outTree)
Y_validation = np.array(y)

dataset = pd.DataFrame({'outTree': outTree, 'Y_validation': list(Y_validation)}, columns=['outTree', 'Y_validation'])
dataset[dataset['outTree']!=dataset['Y_validation']]

      outTree Y_validation
38        30%        [20%]
96        40%        [50%]
118       20%        [30%]
124   low_50%        [50%]
147       20%        [10%]
159       30%        [40%]
162       50%        [40%]
182   low_50%        [50%]
193       40%        [50%]
194       40%        [50%]
209       50%        [40%]
249   low_50%        [50%]
251   low_50%        [50%]
261       40%        [30%]
269       20%        [30%]
270   low_50%        [50%]
315   low_50%        [20%]
334   low_50%        [50%]
348       40%        [30%]
354       40%        [50%]
356       40%        [50%]
361       40%        [50%]
382       50%        [40%]
421       30%        [20%]
471       50%        [40%]
496       50%        [40%]
522   low_50%        [50%]
523       50%        [40%]
574       40%        [50%]
630       50%    [low_50%]
...       ...          ...
661       40%        [50%]
681   low_50%        [50%]
703       50%    [low_50%]
715       20%        [30%]
737   low_50%        [40%]
741       50%        [40%]
744       20%        [50%]
760       30%        [20%]
765   low_50%        [50%]
767       50%    [low_50%]
769   low_50%        [50%]
779       20%        [10%]
815       40%        [30%]
840       30%        [40%]
938       50%    [low_50%]
951   low_50%        [50%]
961   low_50%        [50%]
994   low_50%        [50%]
999       20%        [50%]
1004      20%    [low_50%]
1029      50%        [40%]
1050  low_50%        [50%]
1099      50%        [40%]
1232      20%        [10%]
1244      30%        [20%]
1274  low_50%        [50%]
1306  low_50%        [50%]
1323  low_50%        [50%]
1331      50%    [low_50%]
1460      40%        [30%]

[65 rows x 2 columns]

In [12]:
dataset[dataset['outTree']!=dataset['Y_validation']].shape

(65, 2)

In [ ]:
X.shape

In [ ]:
x.shape

In [ ]:
#df.to_hdf(Week_Tend_First,'a')

# SVM

In [ ]:
'''
from sklearn import svm

clf = svm.SVC()
clf.fit(X, Y)  
'''

In [ ]:
'''
from sklearn import svm
from sklearn.svm import SVR
clf = SVR(kernel='rbf', C=1e3, gamma=0.1,cache_size=7000)
clf.fit(X, Y)
'''

In [ ]:
'''
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.cross_validation import StratifiedKFold
from sklearn.feature_selection import RFECV
from sklearn.datasets import make_classification
# Create the RFE object and compute a cross-validated score.
svc = svm.SVC(kernel="linear")
# The "accuracy" scoring is proportional to the number of correct
# classifications
rfecv = RFECV(estimator=svc, step=1, scoring='accuracy')
rfecv.fit(df2.loc[:,['First_Week', 'Forth_Week', 'Second_Week',
       'Third_Week', 'Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
        'Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'std', 'median', 'mad', 'var', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',#'First_tendency', 'Second_tendency', 'Third_tendency', 
       'P_decrease', 'P_increase']], df2.loc[:,['Forth_tendency']])

print("Optimal number of features : %d" % rfecv.n_features_)
'''

In [ ]:
df2.iloc[:,5:].sort_values('Rank_Final_Week',ascending=True)

In [ ]:
#df2.to_csv('week_count.csv',sep=',',encoding='utf-8',index=False)

In [ ]:
#df2.to_csv('week_count.csv',sep=',',encoding='utf-8',index=False)
#df3.sort_values('Rank_Forth_Week',ascending=True)
df3.to_csv('niche_predict.csv',sep=',',encoding='utf-8',index=False)

In [25]:
clrTree.feature_importances_

array([4.35638213e-04, 2.77564930e-04, 0.00000000e+00, 3.99919519e-04,
       2.78051946e-03, 2.03495232e-04, 1.32205290e-03, 0.00000000e+00,
       2.12711192e-03, 9.49683904e-01, 0.00000000e+00, 0.00000000e+00,
       1.43197955e-02, 1.69958192e-02, 3.52096781e-03, 2.81652222e-03,
       1.52775935e-03, 5.42186657e-04, 1.09602108e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.04635028e-03, 8.67606031e-04, 3.67661103e-05, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

In [24]:
for name, importance in zip(df2.loc[:,['Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
       'Third_Week','Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',
       'P_decrease', 'P_increase']].columns, clrTree.feature_importances_):
    print(name, importance)

Rank_First_Week 0.00043563821251782833
Rank_Second_Week 0.0002775649296360501
Rank_Third_Week 0.0
Third_Week 0.0003999195190774122
Rank_Forth_Week 0.0027805194582456285
Avg_Rank 0.00020349523226081295
Avg_First_Week 0.00132205290255113
Avg_Second_Week 0.0
Avg_Third_Week 0.0021271119216240714
Avg_Forth_Week 0.9496839036122969
Total_Number 0.0
Rank_number 0.0
Avg_Number 0.01431979551845603
Max_Rank 0.016995819162587803
Min_Rank 0.0035209678074803554
Avg_mid_Rank 0.0028165222183002647
sd 0.0015277593544411902
median 0.0005421866568309057
mad 0.0010960210760233497
variance 0.0
First_Rank_Gap 0.0
Second_Rank_Gap 0.0
Third_Rank_Gap 0.0
Forth_Rank_Gap 0.0
First 0.0010463502761046588
Second 0.0008676060313064062
Third 3.676611025934734e-05
decrease 0.0
increase 0.0
P_decrease 0.0
P_increase 0.0

## Decision Tree Report

In [13]:
from __future__ import print_function

import os
import subprocess

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier, export_graphviz

In [14]:
def visualize_tree(tree, feature_names):
    """Create tree png using graphviz.

    Args
    ----
    tree -- scikit-learn DecsisionTree.
    feature_names -- list of feature names.
    """
    with open("dt.dot", 'w') as f:
        export_graphviz(tree, out_file=f,
                        feature_names=feature_names)

    command = ["dot", "-Tpng", "dt.dot", "-o", "dt.png"]
    try:
        subprocess.check_call(command)
    except:
        exit("Could not run dot, ie graphviz, to "
             "produce visualization")

In [15]:
visualize_tree(clrTree,['Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week',
       'Third_Week', 
        'Rank_Forth_Week', 'Avg_Rank', 'Avg_First_Week',
       'Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week',
       'Total_Number', 'Rank_number', 'Avg_Number', 'Max_Rank', 'Min_Rank',
       'Avg_mid_Rank', 'sd', 'median', 'mad', 'variance', 'First_Rank_Gap',
       'Second_Rank_Gap', 'Third_Rank_Gap', 'Forth_Rank_Gap',
       'First', 'Second', 'Third','decrease', 'increase',
       'P_decrease', 'P_increase'])

# --

In [ ]:
make_paper=df3.loc[:,['artist_id','Rank_First_Week', 'Rank_Second_Week', 'Rank_Third_Week','Rank_Forth_Week','median','mad','sd','variance']].sort_values('mad',ascending=True)
make_paper

In [ ]:
make_paper['sd']=round(make_paper['sd'],3)
make_paper['variance']=round(make_paper['variance'],3)
'''
make_paper['artist_id']=make_paper['artist_id'].astype(str)
make_paper['artist_id']=make_paper['artist_id'].apply(lambda n:n[:n.index('.')])
make_paper['number']=make_paper['number'].astype(int)
'''
make_paper

In [ ]:
df3.loc[:,['artist_id','Avg_First_Week','Avg_Second_Week', 'Avg_Third_Week', 'Avg_Forth_Week']].to_csv('avg_Number.csv',sep=',',encoding='utf-8',index=False)

# Compare with arg